name: CI
on:
  push:
    branches: main
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest"]
        ruby: [3.1, 3.2, 3.3, 3.4]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Git repository
      uses: actions/checkout@main

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run linter
      run: bundle exec rake standard

    - name: Run tests
      run: bundle exec rake spec
